#############################################################################
# Makefile for building: qtdesktop
# Generated by qmake (2.01a) (Qt 4.7.3) on: ?? 10? 3 15:50:12 2015
# Project:  qtdesktop.pro
# Template: app
# Command: /home/work/workshop/qtgui/qtdesktop/qmake -o Makefile qtdesktop.pro
#############################################################################

####### Compiler, tools and options

CC            = /home/work/workshop/licheelinux/out/linux/common/buildroot/external-toolchain/bin/arm-linux-gnueabi-gcc
CXX           = /home/work/workshop/licheelinux/out/linux/common/buildroot/external-toolchain/bin/arm-linux-gnueabi-g++
DEFINES       = -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = --sysroot=/home/work/workshop/licheelinux/out/linux/common/buildroot/host/usr/arm-unknown-linux-gnueabi/sysroot -marm -pipe -Os -mabi=aapcs-linux -msoft-float -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64 -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = --sysroot=/home/work/workshop/licheelinux/out/linux/common/buildroot/host/usr/arm-unknown-linux-gnueabi/sysroot -marm -pipe -Os -mabi=aapcs-linux -msoft-float -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64 -O2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I../../licheelinux/out/linux/common/buildroot/host/usr/mkspecs/qws/linux-arm-g++ -I. -I../../licheelinux/out/linux/common/buildroot/host/usr/arm-unknown-linux-gnueabi/sysroot/usr/include/QtCore -I../../licheelinux/out/linux/common/buildroot/host/usr/arm-unknown-linux-gnueabi/sysroot/usr/include/QtNetwork -I../../licheelinux/out/linux/common/buildroot/host/usr/arm-unknown-linux-gnueabi/sysroot/usr/include/QtGui -I../../licheelinux/out/linux/common/buildroot/host/usr/arm-unknown-linux-gnueabi/sysroot/usr/include -I. -I.
LINK          = /home/work/workshop/licheelinux/out/linux/common/buildroot/external-toolchain/bin/arm-linux-gnueabi-g++ --sysroot=/home/work/workshop/licheelinux/out/linux/common/buildroot/host/usr/arm-unknown-linux-gnueabi/sysroot
LFLAGS        = -L/home/work/workshop/licheelinux/out/linux/common/buildroot/host/usr/arm-unknown-linux-gnueabi/sysroot/lib -L/home/work/workshop/licheelinux/out/linux/common/buildroot/host/usr/arm-unknown-linux-gnueabi/sysroot/usr/lib -Wl,-O1
LIBS          = $(SUBLIBS)  -L/home/work/workshop/licheelinux/out/linux/common/buildroot/host/usr/arm-unknown-linux-gnueabi/sysroot/usr/lib libjpeg.a -lQtGui -L/home/work/workshop/licheelinux/out/linux/common/buildroot/host/usr/arm-unknown-linux-gnueabi/sysroot/usr/lib -lQtNetwork -lQtCore -lpthread 
AR            = /home/work/workshop/licheelinux/out/linux/common/buildroot/external-toolchain/bin/arm-linux-gnueabi-ar cqs
RANLIB        = /home/work/workshop/licheelinux/out/linux/common/buildroot/external-toolchain/bin/arm-linux-gnueabi-ranlib
QMAKE         = /home/work/workshop/qtgui/qtdesktop/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = /home/work/workshop/licheelinux/out/linux/common/buildroot/external-toolchain/bin/arm-linux-gnueabi-strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		mainwindow.cpp \
		V4L2.c \
		decoder_mjpeg.c \
		camera.c \
		main_camera.c moc_mainwindow.cpp
OBJECTS       = main.o \
		mainwindow.o \
		V4L2.o \
		decoder_mjpeg.o \
		camera.o \
		main_camera.o \
		moc_mainwindow.o
DIST          = ../../licheelinux/out/linux/common/buildroot/host/usr/mkspecs/common/g++.conf \
		../../licheelinux/out/linux/common/buildroot/host/usr/mkspecs/common/unix.conf \
		../../licheelinux/out/linux/common/buildroot/host/usr/mkspecs/common/linux.conf \
		../../licheelinux/out/linux/common/buildroot/host/usr/mkspecs/common/qws.conf \
		../../licheelinux/out/linux/common/buildroot/host/usr/mkspecs/qconfig.pri \
		../../licheelinux/out/linux/common/buildroot/host/usr/mkspecs/modules/qt_webkit_version.pri \
		../../licheelinux/out/linux/common/buildroot/host/usr/mkspecs/features/qt_functions.prf \
		../../licheelinux/out/linux/common/buildroot/host/usr/mkspecs/features/qt_config.prf \
		../../licheelinux/out/linux/common/buildroot/host/usr/mkspecs/features/exclusive_builds.prf \
		../../licheelinux/out/linux/common/buildroot/host/usr/mkspecs/features/default_pre.prf \
		../../licheelinux/out/linux/common/buildroot/host/usr/mkspecs/features/release.prf \
		../../licheelinux/out/linux/common/buildroot/host/usr/mkspecs/features/default_post.prf \
		../../licheelinux/out/linux/common/buildroot/host/usr/mkspecs/features/warn_on.prf \
		../../licheelinux/out/linux/common/buildroot/host/usr/mkspecs/features/qt.prf \
		../../licheelinux/out/linux/common/buildroot/host/usr/mkspecs/features/unix/thread.prf \
		../../licheelinux/out/linux/common/buildroot/host/usr/mkspecs/features/moc.prf \
		../../licheelinux/out/linux/common/buildroot/host/usr/mkspecs/features/resources.prf \
		../../licheelinux/out/linux/common/buildroot/host/usr/mkspecs/features/uic.prf \
		../../licheelinux/out/linux/common/buildroot/host/usr/mkspecs/features/yacc.prf \
		../../licheelinux/out/linux/common/buildroot/host/usr/mkspecs/features/lex.prf \
		../../licheelinux/out/linux/common/buildroot/host/usr/mkspecs/features/include_source_dir.prf \
		qtdesktop.pro
QMAKE_TARGET  = qtdesktop
DESTDIR       = 
TARGET        = qtdesktop

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): ui_mainwindow.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: qtdesktop.pro  ../../licheelinux/out/linux/common/buildroot/host/usr/mkspecs/qws/linux-arm-g++/qmake.conf ../../licheelinux/out/linux/common/buildroot/host/usr/mkspecs/common/g++.conf \
		../../licheelinux/out/linux/common/buildroot/host/usr/mkspecs/common/unix.conf \
		../../licheelinux/out/linux/common/buildroot/host/usr/mkspecs/common/linux.conf \
		../../licheelinux/out/linux/common/buildroot/host/usr/mkspecs/common/qws.conf \
		../../licheelinux/out/linux/common/buildroot/host/usr/mkspecs/qconfig.pri \
		../../licheelinux/out/linux/common/buildroot/host/usr/mkspecs/modules/qt_webkit_version.pri \
		../../licheelinux/out/linux/common/buildroot/host/usr/mkspecs/features/qt_functions.prf \
		../../licheelinux/out/linux/common/buildroot/host/usr/mkspecs/features/qt_config.prf \
		../../licheelinux/out/linux/common/buildroot/host/usr/mkspecs/features/exclusive_builds.prf \
		../../licheelinux/out/linux/common/buildroot/host/usr/mkspecs/features/default_pre.prf \
		../../licheelinux/out/linux/common/buildroot/host/usr/mkspecs/features/release.prf \
		../../licheelinux/out/linux/common/buildroot/host/usr/mkspecs/features/default_post.prf \
		../../licheelinux/out/linux/common/buildroot/host/usr/mkspecs/features/warn_on.prf \
		../../licheelinux/out/linux/common/buildroot/host/usr/mkspecs/features/qt.prf \
		../../licheelinux/out/linux/common/buildroot/host/usr/mkspecs/features/unix/thread.prf \
		../../licheelinux/out/linux/common/buildroot/host/usr/mkspecs/features/moc.prf \
		../../licheelinux/out/linux/common/buildroot/host/usr/mkspecs/features/resources.prf \
		../../licheelinux/out/linux/common/buildroot/host/usr/mkspecs/features/uic.prf \
		../../licheelinux/out/linux/common/buildroot/host/usr/mkspecs/features/yacc.prf \
		../../licheelinux/out/linux/common/buildroot/host/usr/mkspecs/features/lex.prf \
		../../licheelinux/out/linux/common/buildroot/host/usr/mkspecs/features/include_source_dir.prf \
		/home/work/workshop/licheelinux/out/linux/common/buildroot/host/usr/arm-unknown-linux-gnueabi/sysroot/usr/lib/libQtGui.prl \
		/home/work/workshop/licheelinux/out/linux/common/buildroot/host/usr/arm-unknown-linux-gnueabi/sysroot/usr/lib/libQtNetwork.prl \
		/home/work/workshop/licheelinux/out/linux/common/buildroot/host/usr/arm-unknown-linux-gnueabi/sysroot/usr/lib/libQtCore.prl
	$(QMAKE) -o Makefile qtdesktop.pro
../../licheelinux/out/linux/common/buildroot/host/usr/mkspecs/common/g++.conf:
../../licheelinux/out/linux/common/buildroot/host/usr/mkspecs/common/unix.conf:
../../licheelinux/out/linux/common/buildroot/host/usr/mkspecs/common/linux.conf:
../../licheelinux/out/linux/common/buildroot/host/usr/mkspecs/common/qws.conf:
../../licheelinux/out/linux/common/buildroot/host/usr/mkspecs/qconfig.pri:
../../licheelinux/out/linux/common/buildroot/host/usr/mkspecs/modules/qt_webkit_version.pri:
../../licheelinux/out/linux/common/buildroot/host/usr/mkspecs/features/qt_functions.prf:
../../licheelinux/out/linux/common/buildroot/host/usr/mkspecs/features/qt_config.prf:
../../licheelinux/out/linux/common/buildroot/host/usr/mkspecs/features/exclusive_builds.prf:
../../licheelinux/out/linux/common/buildroot/host/usr/mkspecs/features/default_pre.prf:
../../licheelinux/out/linux/common/buildroot/host/usr/mkspecs/features/release.prf:
../../licheelinux/out/linux/common/buildroot/host/usr/mkspecs/features/default_post.prf:
../../licheelinux/out/linux/common/buildroot/host/usr/mkspecs/features/warn_on.prf:
../../licheelinux/out/linux/common/buildroot/host/usr/mkspecs/features/qt.prf:
../../licheelinux/out/linux/common/buildroot/host/usr/mkspecs/features/unix/thread.prf:
../../licheelinux/out/linux/common/buildroot/host/usr/mkspecs/features/moc.prf:
../../licheelinux/out/linux/common/buildroot/host/usr/mkspecs/features/resources.prf:
../../licheelinux/out/linux/common/buildroot/host/usr/mkspecs/features/uic.prf:
../../licheelinux/out/linux/common/buildroot/host/usr/mkspecs/features/yacc.prf:
../../licheelinux/out/linux/common/buildroot/host/usr/mkspecs/features/lex.prf:
../../licheelinux/out/linux/common/buildroot/host/usr/mkspecs/features/include_source_dir.prf:
/home/work/workshop/licheelinux/out/linux/common/buildroot/host/usr/arm-unknown-linux-gnueabi/sysroot/usr/lib/libQtGui.prl:
/home/work/workshop/licheelinux/out/linux/common/buildroot/host/usr/arm-unknown-linux-gnueabi/sysroot/usr/lib/libQtNetwork.prl:
/home/work/workshop/licheelinux/out/linux/common/buildroot/host/usr/arm-unknown-linux-gnueabi/sysroot/usr/lib/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -o Makefile qtdesktop.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/qtdesktop1.0.0 || $(MKDIR) .tmp/qtdesktop1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/qtdesktop1.0.0/ && $(COPY_FILE) --parents mainwindow.h videodev.h V4L2.h jpeglib.h jmorecfg.h jerror.h jconfig.h huffman.h decoder_mjpeg.h decoder.h camera.h main_camera.h .tmp/qtdesktop1.0.0/ && $(COPY_FILE) --parents main.cpp mainwindow.cpp V4L2.c decoder_mjpeg.c camera.c main_camera.c .tmp/qtdesktop1.0.0/ && $(COPY_FILE) --parents mainwindow.ui .tmp/qtdesktop1.0.0/ && (cd `dirname .tmp/qtdesktop1.0.0` && $(TAR) qtdesktop1.0.0.tar qtdesktop1.0.0 && $(COMPRESS) qtdesktop1.0.0.tar) && $(MOVE) `dirname .tmp/qtdesktop1.0.0`/qtdesktop1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/qtdesktop1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_mainwindow.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mainwindow.cpp
moc_mainwindow.cpp: mainwindow.h
	/home/work/workshop/licheelinux/out/linux/common/buildroot/host/usr/bin/moc $(DEFINES) $(INCPATH) mainwindow.h -o moc_mainwindow.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_mainwindow.h
compiler_uic_clean:
	-$(DEL_FILE) ui_mainwindow.h
ui_mainwindow.h: mainwindow.ui
	/home/work/workshop/licheelinux/out/linux/common/buildroot/host/usr/bin/uic mainwindow.ui -o ui_mainwindow.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_uic_clean 

####### Compile

main.o: main.cpp mainwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

mainwindow.o: mainwindow.cpp mainwindow.h \
		ui_mainwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o mainwindow.cpp

V4L2.o: V4L2.c V4L2.h \
		videodev.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o V4L2.o V4L2.c

decoder_mjpeg.o: decoder_mjpeg.c jpeglib.h \
		jconfig.h \
		jmorecfg.h \
		jerror.h \
		huffman.h \
		decoder_mjpeg.h \
		decoder.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o decoder_mjpeg.o decoder_mjpeg.c

camera.o: camera.c camera.h \
		videodev.h \
		V4L2.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o camera.o camera.c

main_camera.o: main_camera.c main_camera.h \
		camera.h \
		videodev.h \
		V4L2.h \
		decoder.h \
		decoder_mjpeg.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o main_camera.o main_camera.c

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

